### PR TITLE
#feature   style comments

### PR DESCRIPTION
**Pull request by HarperThurlow**
Hi Guys, I have worked on the comments styling

Comment details:
Comments background for meta data and comment excerpt
Comment query for smaller screens to remove depth so it fits on a smaller screen
Comment form colors and sizing

Could you all please review these changes and provide feedback/the all-clear to merge this pull request.

Regards,
@HarperThurlow

Post-Note:
I accidently commited the .css and .css map to the commits. This will need to be fixed before merging into style-content (just delete .css file).

### CODE REVIEW

**Review by DaRealTaylor — APPROVED** [review]
Turned out great Harper, not sure about colour scheme though.

**Review by Dallas-Marshall — APPROVED** [review]
Awesome work! That looks great 💯

**Review by orth22 — CHANGES_REQUESTED** [review]
Good job Harper coming along nicely, just some recommendations I have here.

The grey background on the comments section doesn't work with me. I probably would take the background colour out and not have one at all.

The "Leave a reply" title is a bit distracting. Could it look better on the left? or maybe it could be a bit smaller?

There's a lot of CSS classes with nothing in them? Is this intentional?

**Review by orth22 — APPROVED** [review]
Looks really good now!

**Pull request merged**
