### PR TITLE
#feature   sidebar and widgets

### PR DESCRIPTION
**Pull request by DaRealTaylor**
Hi Guys, I have worked on the sidebar and widgets

### Widget details:  
- Spacing 
- Font style/family
- Colour, some still need a variable to be made in the "&:focus("

Could you all please review these changes and provide feedback/the all-clear to merge this pull request.
Regards, 
@DaRealTaylor 

Edit by Ryan:
If you're using Theme Unit Test, make sure to go to the "Block category: Widget" page to test Taylor's changes more effictively.

### CODE REVIEW

**Comment by orth22** [comment]
Hey Taylor, 
I just edited your initial comment to include how to see your widgets if anyone is using WordPress Theme Unit Test.
Looks good to me, the font stands out,  the padding and margin fit in.
Hoping to get your guys reviews on my branch and merge so we can finally see some colour in your widgets.

**Review by orth22 — APPROVED** [review]
Font fits well. Padding and Margin are nicely spaced. 
Make sure your commit messages are more descriptive in the future. It's important since we need a written history of what you have done and what your code means displayed alongside what we have done when we merge your branch in Main / Staging / Production.

**Review by Dallas-Marshall — APPROVED** [review]
This looks great, awesome work Taylor.

**Comment by HarperThurlow** [comment]
Potential issues:

- When screen minimized sidebar & main overlap each other
         - Potential fix: Have sidebar collapse when screen gets too low and can press it out. (Just like nav bar)
image

- No padding off the edge of the screen
         - Potential fix: Give whole sidebar just a touch of padding either side so it doesn't seem squished
 
image

- On Hover is not highlighted as the same as others (This is ok but should have consistent with the rest of the work).
        - Potential fix: Copy on hover properties from nav bar/footer nav to sidebars.

**Comment by orth22** [comment]
> Potential issues:
> 
> * When screen minimized sidebar & main overlap each other
>   - Potential fix: Have sidebar collapse when screen gets too low and can press it out. (Just like nav bar)
>   image
> * No padding off the edge of the screen
>   - Potential fix: Give whole sidebar just a touch of padding either side so it doesn't seem squished
> 
> image
> 
> * On Hover is not highlighted as the same as others (This is ok but should have consistent with the rest of the work).
>   - Potential fix: Copy on hover properties from nav bar/footer nav to sidebars.

It's fixed now!

**Comment by HarperThurlow** [comment]
Double checked everything. Thanks for fixing them. Merging pull request now :)

**Pull request merged**
