### PR TITLE
#feature   Single Post Template

### PR DESCRIPTION
**Pull request by orth22**
- Changed positioning of meta data. Published on, written by, date, all on same line.

- Add dividers between meta data.

- Image alignment and image captions are better scaled on different screen sizes.

- Default WordPress galleries are styled.

- Modified post navigation function to include Next / Previous posts at the bottom of a post.

- Include styling such as box styling, colours and optimised for screen queries of end of post navigation.

Any feedback would be appreciated :)

@RyanQ02

### CODE REVIEW

**Comment by HarperThurlow** [comment]
Comments:
Not 100% sure on this but I don't think your files are set up right. @Dallas-Marshall can double check this as the file expert man
> Fix: I think you may have to get these .scss files to map to the original .css file by using the "@include" method. We can go over this tomorrow in the meeting
image

I am getting this error from the galleries.css file from a direct pull from the repo.
> Fix: Make sure variables are defined at the top of the scope on .scss files
image

I don't think I can actually see the content of this until it is fixed. Will talk about it in the meeting tomorrow :)

**Review by Dallas-Marshall — CHANGES_REQUESTED** [review]
Hey @RyanQ02, this template is looking good so far. There are a few things I have noticed:

- [x] Have captions.scss and galleries.scss been named in line with other similar files?  galleries.scss to _galleries.scss etc??
- [x] Are captions.scss and galleries.scss located within the correct file structure location?  
- [x] Could the default underline colour maybe be changed from the default?
- [x] Similarly, could the default visited link colour be changed from the default?
- [x] The square button is displaying rounded, have you set a custom style for buttons?
image

This is looking great so far!

**Comment by orth22** [comment]
> Hey @RyanQ02, this template is looking good so far. There are a few things I have noticed:
> 
> * [x]  Have captions.scss and galleries.scss been named in line with other similar files?  galleries.scss to _galleries.scss etc??
> * [x]  Are captions.scss and galleries.scss located within the correct file structure location?
> * [x]  Could the default underline colour maybe be changed from the default?
> * [x]  Similarly, could the default visited link colour be changed from the default?
> * [x]  The square button is displaying rounded, have you set a custom style for buttons?
>   image
> 
> This is looking great so far!

Just a question @Dallas-Marshall, What do you mean by "Could the default underline colour maybe be changed from the default?" and "Similarly, could the default visited link colour be changed from the default?"? 
I have set $color__action for both included from color.scss? did you want $color__link: #4169e1 and $color__link-visited (purple) back instead?

The rounded button wasn't set by me, it was set somewhere when we were editing the header and footer.

Thanks.

**Comment by HarperThurlow** [comment]
Hey @RyanQ02,

To reply to your comment with some help: 
- to change the underline color you use "text-decoration-color: color;"
- to change visited link color do "a:visited {color: color;}"

I checked the pull and not sure that your variables are being used. Maybe double check that they are being imported properly?

Regards, Harper

**Comment by orth22** [comment]
> Hey @RyanQ02,
> 
> To reply to your comment with some help:
> 
> * to change the underline color you use "text-decoration-color: color;"
> * to change visited link color do "a:visited {color: color;}"
> 
> I checked the pull and not sure that your variables are being used. Maybe double-check that they are being imported properly?
> 
> Regards, Harper

Yeh sorry, I meant to say to use those variable instead that you mentioned.
@Dallas-Marshall Did you want me to change the variables from colour__action to the underlined and visited colour @HarperThurlow has mentioned?
Thanks.

**Comment by Dallas-Marshall** [comment]
> > Hey @RyanQ02,
> > To reply to your comment with some help:
> > 
> > * to change the underline color you use "text-decoration-color: color;"
> > * to change visited link color do "a:visited {color: color;}"
> > 
> > I checked the pull and not sure that your variables are being used. Maybe double-check that they are being imported properly?
> > Regards, Harper
> 
> Yeh sorry, I meant to say to use those variable instead that you mentioned.
> @Dallas-Marshall Did you want me to change the variables from colour__action to the underlined and visited colour @HarperThurlow has mentioned?
> Thanks.

You can call them whatever you want, just tell @DaRealTaylor what they are so he can update his variable names.

**Comment by orth22** [comment]
> > > Hey @RyanQ02,
> > > To reply to your comment with some help:
> > > 
> > > * to change the underline color you use "text-decoration-color: color;"
> > > * to change visited link color do "a:visited {color: color;}"
> > > 
> > > I checked the pull and not sure that your variables are being used. Maybe double-check that they are being imported properly?
> > > Regards, Harper
> > 
> > 
> > Yeh sorry, I meant to say to use those variable instead that you mentioned.
> > @Dallas-Marshall Did you want me to change the variables from colour__action to the underlined and visited colour @HarperThurlow has mentioned?
> > Thanks.
> 
> You can call them whatever you want, just tell @DaRealTaylor what they are so he can update his variable names.

This is what Taylor has to define in side bar and widgets.
$color__skin: # 002254;
$color__action: # 1BB1DE;
It's already defined in the single post template branch's colors.scss. Me and Taylor agreed that when mine is merged into develop, then he will update the variables? 
Are there any more issues or concerns?
@Dallas-Marshall @DaRealTaylor @HarperThurlow

**Review by DaRealTaylor — APPROVED** [review]
Just had look @RyanQ02, everything here looks alright on my end. My branch has already been merged so will have to update the variables in Develop---style-content branch but should be no dramas

**Comment by orth22** [comment]
> Just had look @RyanQ02, everything here looks alright on my end. My branch has already been merged so will have to update the variables in Develop---style-content branch but should be no dramas

Nah there shouldn't be, just need to update your colors, that's all there is to it.

**Review by HarperThurlow — APPROVED** [review]
All looks good to me now. Filing is correct and everything looks good. Well done mate 👍

**Review by Dallas-Marshall — APPROVED** [review]
Looks 🔥

**Pull request merged**
