### PR TITLE
Create header & Navigation

### PR DESCRIPTION
**Pull request by Dallas-Marshall**
Hi Guys, I have worked with @RyanQ02 to style our themes Header and Navigation.  

### Header details:  
- Header image displays 100% of the width of the screen at all resolution sizes and takes up a maximum of 50% of the vertical height available.   
- Header image only displays on the home page declared in WordPress settings.  
- Site logo support added in the customiser.  
- If no logo is set the site title takes its place.  
- Site description is stacked below the site title on smaller displays and floated right on larger displays.  

### Navigation details:  
- On screens smaller than a tablet (Google specified sizes) navigation menu is hidden. Once you click the menu button it will drop down vertically with arrows to expand.
- A horizontal navigation is displayed on larger screens with hover properties to display dropdown menus.

Could you all please review these changes and provide feedback/the all-clear to merge this pull request.
Regards, 
@Dallas-Marshall and @RyanQ02

### CODE REVIEW

**Comment by Dallas-Marshall** [comment]
[Review header, footer and navigation](https://trello.com/c/B3teZEqV/53-review-header-footer-and-navigation)

**Comment by Dallas-Marshall** [comment]
- [x] On hover border
- [x] Dropdown Menu is better on smaller screen sizes. (Fix spacing if any etc.)
- [ ] Add Menu button for smaller screens

**Comment by HarperThurlow** [comment]
Hover padding is too much and when attempting to hover over if you don't speed to the next menu it dissapears. Picture shown below and @RyanQ02 notified.
Screenshot below:
pullreq-1

**Comment by orth22** [comment]
Turns out it wasn't enough padding. I added some more and the drop down works better!
I've committed it and I'll push it when I finish some more work on hover borders.

**Comment by Dallas-Marshall** [comment]
I'm not sure what happened there @RyanQ02, I will test it now to make sure it still works. We can then do one last review this morning and merge.

**Comment by Dallas-Marshall** [comment]
## Ok I have located what was done wrong by somebody last night.

When you check out a branch in PHP Storm Please simply select **"Checkout"**. Once you have checked out the branch you want to work on, please click **GIT-> Pull** from the top horizontal menu of PHP Storm. DO NOT use one of the pull options when checking out the branch this merges the branch you are checking out with the currently checked out branch, hence what happened last night. I think this is why when the last commit was done it has re-pushed every commit from header and footer branches into this branch.

image
image

**Comment by HarperThurlow** [comment]
Everything working as intended. Ready to merge with create-header-and-footer branch when footer pull request is complete.

**Pull request merged**
