### PR TITLE
#feature attach footer to base

### PR DESCRIPTION
**Pull request by Dallas-Marshall**
Hi Guys, I have made some changes to the footer for our theme. 

### footer details:  
- Attach the footer to the bottom of the window where the content is small.
- Vertically align the site-description to match other columns.

Could you all please review these changes and provide feedback/approve the merge.  

Regards, 
@Dallas-Marshall

### CODE REVIEW

**Comment by HarperThurlow** [comment]
Hi Dallas,

The branch does not work on the theme unit test as the footer is huge. We need to be careful doing this as my entire screen is completely filled out with the footer no much how I scroll. This is why we didn't have the position as fixed when we did it just in case. When you are free I can screenshare to show you this problem.

**Review by orth22 — APPROVED** [review]
The footer attached looks good and the fix implementation works well!

**Comment by Dallas-Marshall** [comment]
> Hi Dallas,
> 
> The branch does not work on the theme unit test as the footer is huge. We need to be careful doing this as my entire screen is completely filled out with the footer no much how I scroll. This is why we didn't have the position as fixed when we did it just in case. When you are free I can screenshare to show you this problem.

Hi @HarperThurlow, the way you normally fix this is by adding padding to the bottom, The reason I have not is you do not normally have so many items in the footer menu to make it fill most of the screen. Adding a lot of padding to the body to accommodate for this extreme edge case would result in there is a massive gap in most cases. I, therefore, decided not to handle this 😀

**Comment by Dallas-Marshall** [comment]
image

This is how it looks with a reasonable number of links in the social menu.

**Comment by Dallas-Marshall** [comment]
@DaRealTaylor can you please review these changes.

**Review by HarperThurlow — APPROVED** [review]
With your comment in mind everything is ok. I see no other problems with this branch 👍

**Review by DaRealTaylor — APPROVED** [review]
Reviewed as requested, everything works great as intended. Just hope no one wants to add a million links to the footer.

**Pull request merged**
