### PR TITLE
#feature 404 page

### PR DESCRIPTION
**Pull request by Dallas-Marshall**
Hi Guys, I have created a custom 404 page for our theme. 

### 404 page details:  
- Features a custom message.
- Centered text.
- Back to homepage link.

image

Could you all please review these changes and provide feedback/approve the merge.  

Regards, 
@Dallas-Marshall

### CODE REVIEW

**Comment by HarperThurlow** [comment]
Hey Dallas,
Looks good however I tried this on the theme unit test and looks like if the sidebar is active it it having it go there instead of main (Not 100% sure but its what it looks like). Have a look at the photo below.
image

**Comment by Dallas-Marshall** [comment]
> Hey Dallas,
> Looks good however I tried this on the theme unit test and looks like if the sidebar is active it it having it go there instead of main (Not 100% sure but its what it looks like). Have a look at the photo below.

Hi @HarperThurlow, Thank you for pointing out that issue, I believe this should be sorted now.

**Comment by Dallas-Marshall** [comment]
@RyanQ02 and @DaRealTaylor can you please review these changes?

**Review by orth22 — APPROVED** [review]

**Review by DaRealTaylor — APPROVED** [review]
Hi Dallas, just had a check. Everything turned out fine on my end. Good work xx

**Review by HarperThurlow — APPROVED** [review]
Nice Dallas, all looks good to me now. Ready to merge into style-content on my end

**Pull request merged**
